/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'henry' at '2016/5/15 下午 5:59' with Gradle 2.13
 *
 * @author henry, @date 2016/5/15 下午 5:59
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
